In [3]:
packages = ["numpy", "matplotlib", "scipy", "sympy", "jupyter_core"]
for pkg in packages:
    try:
        __import__(pkg)
        print(f"{pkg}: ✅ 已安装")
    except ImportError:
        print(f"{pkg}: ❌ 未安装")

numpy: ✅ 已安装
matplotlib: ✅ 已安装
scipy: ✅ 已安装
sympy: ✅ 已安装
jupyter_core: ✅ 已安装


In [3]:
import numpy
from matplotlib import pyplot

In [4]:
myarray = numpy.linspace(0, 5, 10)
print(myarray)

[0.         0.55555556 1.11111111 1.66666667 2.22222222 2.77777778
 3.33333333 3.88888889 4.44444444 5.        ]


In [5]:
a = 5        #a is an integer 5
b = 'five'   #b is a string of the word 'five'
c = 5.0      #c is a floating point 5
print(type(a))
print(type(b))
print(type(c))

<class 'int'>
<class 'str'>
<class 'float'>


In [6]:
for i in range(5):
    print("Hi \n")

Hi 

Hi 

Hi 

Hi 

Hi 



In [7]:
for i in range(3):
    for j in range(3):
        print(i, j)

    print("This statement is within the i-loop, but not the j-loop")

0 0
0 1
0 2
This statement is within the i-loop, but not the j-loop
1 0
1 1
1 2
This statement is within the i-loop, but not the j-loop
2 0
2 1
2 2
This statement is within the i-loop, but not the j-loop


In [8]:
myvals = numpy.array([1, 2, 3, 4, 5])
myvals

array([1, 2, 3, 4, 5])

In [10]:
print(myvals[0], myvals[4])

1 5


In [11]:
myvals[0:3]

array([1, 2, 3])

In [12]:
a = numpy.linspace(1,5,5)
print(a)
b = a
print(b)

[1. 2. 3. 4. 5.]
[1. 2. 3. 4. 5.]


In [13]:
a[2] = 17
print(a)
print(b)

[ 1.  2. 17.  4.  5.]
[ 1.  2. 17.  4.  5.]


In [14]:
c = a.copy()
a[2] = 3
print(a)
print(c)

[1. 2. 3. 4. 5.]
[ 1.  2. 17.  4.  5.]
